apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-config
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  BASE_URL: {{ .Values.env.BASE_URL | quote }}
  AWS_ENDPOINT_URL: {{ .Values.env.AWS_ENDPOINT_URL | quote }}
  AWS_DEFAULT_REGION: {{ .Values.env.AWS_DEFAULT_REGION | quote }}
  S3_BUCKET_NAME: {{ .Values.env.S3_BUCKET_NAME | quote }}
