# deployment.yaml — Helm Deployment Template
#
# Bu dosya ne işe yarar?
#   values.yaml değerlerini Kubernetes Deployment manifest'ine dönüştürür.
#   {{ .Values.xxx }} → values.yaml'dan değer okur.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.fullname" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "url-shortener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "url-shortener.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-config
                  key: DATABASE_URL
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-config
                  key: BASE_URL
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-config
                  key: AWS_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.env.AWS_ACCESS_KEY_ID | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.env.AWS_DEFAULT_REGION | quote }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.env.S3_BUCKET_NAME | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
